version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: -v3-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Test
          command: yarn test:unit --maxWorkers=2 --coverage
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) -cF javascript
workflows:
  version: 2
  tests:
    jobs:
      - test